package com.omkar.inventory.reporting.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReportRequest {

    @NotBlank(message = "Report name is required")
    private String reportName;

    @NotBlank(message = "Report type is required")
    private String reportType;

    @NotBlank(message = "Generated By is required")
    private String generatedBy;

    private LocalDateTime generatedDate;

    @NotBlank(message = "Status is required")
    private String status;
}