server:
  port: 8084

spring:
  application:
    name: purchase-service
    data:
      redis:
        host: localhost
        port: 6379
        timeout: 5000

  datasource:
    url: jdbc:mysql://localhost:3306/purchase_db
    username: root
    password: root

  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.omkar.inventory: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger - %msg%n"

jwt:
  secret: ThisIsMyVeryLongSecretKeyForInventoryManagementSystemJWT2026SpringBootProject

resilience4j:

  circuitbreaker:

    instances:

      productService:

        slidingWindowSize: 10

        minimumNumberOfCalls: 5

        permittedNumberOfCallsInHalfOpenState: 3

        waitDurationInOpenState: 30s

        failureRateThreshold: 50

        automaticTransitionFromOpenToHalfOpenEnabled: true

      inventoryService:

        slidingWindowSize: 10

        minimumNumberOfCalls: 5

        permittedNumberOfCallsInHalfOpenState: 3

        waitDurationInOpenState: 30s

        failureRateThreshold: 50

        automaticTransitionFromOpenToHalfOpenEnabled: true

    resilience4j:

      retry:

        instances:

          productService:

            maxAttempts: 3

            waitDuration: 2s

            retryExceptions:
              - feign.RetryableException
              - java.net.ConnectException
              - java.net.SocketTimeoutException

          inventoryService:

            maxAttempts: 3

            waitDuration: 2s

            retryExceptions:
              - feign.RetryableException
              - java.net.ConnectException
              - java.net.SocketTimeoutException
  resilience4j:
    ratelimiter:
      instances:

        productService:
          limitForPeriod: 100
          limitRefreshPeriod: 1s
          timeoutDuration: 0

        inventoryService:
          limitForPeriod: 100
          limitRefreshPeriod: 1s
          timeoutDuration: 0

bulkhead:

  instances:

    productService:

      maxConcurrentCalls: 20

      maxWaitDuration: 2s

    inventoryService:

      maxConcurrentCalls: 20

      maxWaitDuration: 2s


  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

      auto-offset-reset: earliest