server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        #
        #          # No filter here (public)

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**


        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**


        - id: purchase-service
          uri: lb://PURCHASE-SERVICE
          predicates:
            - Path=/api/purchases/**


        - id: supplier-service
          uri: lb://SUPPLIER-SERVICE
          predicates:
            - Path=/api/suppliers/**


        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**


        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**


        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**


        - id: reporting-service
          uri: lb://REPORTING-SERVICE
          predicates:
            - Path=/api/reports/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ThisIsMyVeryLongSecretKeyForInventoryManagementSystemJWT2026SpringBootProject

management:
  endpoints:
    web:
      exposure:
        include: "*"