spring:
  application:
    name: config-server

  profiles:
    active: native

jwt:
      secret: ThisIsMyVeryLongSecretKeyForInventoryManagementSystemJWT2026SpringBootProject
      expiration: 86400000